script to show button text added
rafprzygoda/9.5_dom pull request #1
Opened 2017-06-03 13:48 UTC by rafprzygoda

2017-06-04 09:58 UTC, matwjablonski requested changes

2017-06-04 09:58 UTC, matwjablonski commented on js/script.js
> +        document.getElementById("button_names").innerHTML = text;
why you add <br> to innerText and then you set it to innerHTML? better if you add it to innerHTML in loop

2017-06-04 09:58 UTC, matwjablonski commented on js/script.js
> +        var i;
this declaration move to loop for

2017-06-04 12:43 UTC, rafprzygoda commented
Fixed

2017-06-05 14:12 UTC, matwjablonski requested changes

2017-06-05 14:12 UTC, matwjablonski commented on js/script.js
> +for (i = 0; i < classButton.length; i++) {
`for (var i = 0; i < classButton.length; i++)` 

not below

2017-06-05 18:28 UTC, rafprzygoda commented on js/script.js
> +for (i = 0; i < classButton.length; i++) {
var text = ""; moved

2017-06-05 20:46 UTC, rafprzygoda commented on js/script.js
> +for (i = 0; i < classButton.length; i++) {
I think now is ok :)

2017-06-05 20:51 UTC, matwjablonski approved these changes

2017-06-17 20:25 UTC, merged